### ISSUE TITLE
Create navbar from design image.

### ISSUE THREAD

**Issue by AjeaSmith** [AjeaSmith/Huddle-landing-page-collab#1]

**Comment by maknetaRo** [comment]
Can I do it together with hero section?

**Comment by AjeaSmith** [comment]
I would say if nobody else claims it, then go for it 👍

**Comment by maknetaRo** [comment]
I've already started because it has the same layout as the hero section. So can I continue?

**Comment by AjeaSmith** [comment]
sure thing! 👍

**Comment by maknetaRo** [comment]
So I can assign myself to this issue?

**Comment by AjeaSmith** [comment]
I just assigned you 👍

**Comment by AjeaSmith** [comment]
Navbar looks great 👍
