### ISSUE TITLE
Create footer section from design image.

### ISSUE THREAD

**Issue by AjeaSmith** [AjeaSmith/Huddle-landing-page-collab#5]

**Comment by cluzier** [comment]
I would like to work on this issue.

**Comment by AjeaSmith** [comment]
Hey Connor! its all yours 👍

**Comment by AjeaSmith** [comment]
*Update*
Connor did a great job getting the footer started! if anyone wants to make a few touch ups feel free to do so. 
- [ ] Remove bulletin points from list
- [ ] Change nav font color
- [ ] Other things you might find :)

Be sure to look check out the design image located in the designFiles folder 👍 :)

**Comment by maknetaRo** [comment]
It works well only on desktop but not on mobile.

**Comment by AjeaSmith** [comment]
Awesome, I'll check it out in a bit

**Comment by cluzier** [comment]
> It works well only on desktop but not on mobile.

I used `px` instead of something that would scale like `vmin`, I did use flexbox too! :)
(this should be an easy fix)

**Comment by AjeaSmith** [comment]
I could work on the putting the font awesome icons and making it responsive :)

**Comment by AjeaSmith** [comment]
update to this issue, I added the font awesome Icons, made it look good for mobile 😄  and fixed some height related issues. I would say this section is good to go and can be closed. If for any reason it needs more changes i will reopen 👍
